export default {
  NEW_ELEMENT: 'NEW_ELEMENT',
  REMOVE_ELEMENT: 'REMOVE_ELEMENT',
  CHANGE_VISIBILITY: 'CHANGE_VISIBILITY',
  TOGGLE_VISIBILITY: 'TOGGLE_VISIBILITY',
  TOGGLE_POSITION: 'TOGGLE_POSITION'
};
